plugins {
    id 'com.android.application' version '8.13.2'
}

def keyProperties = new Properties()
def keyPropertiesFile = rootProject.file('key.properties')
if (keyPropertiesFile.exists()) {
    keyPropertiesFile.withInputStream { keyProperties.load(it) }
}

android {
    namespace 'de.j4velin.calendarWidget'
    compileSdk 34

    defaultConfig {
        applicationId 'de.j4velin.calendarWidget'
        minSdk 21
        targetSdk 34
    }

    buildFeatures {
        buildConfig true
    }

    signingConfigs {
        if (keyPropertiesFile.exists()) {
            release {
                storeFile rootProject.file(keyProperties.keyStore)
                storePassword keyProperties.keyStorePassword
                keyAlias keyProperties.keyAlias
                keyPassword keyProperties.keyAliasPassword
            }
        }
    }

    buildTypes {
        release {
            if (keyPropertiesFile.exists()) {
                signingConfig signingConfigs.release
            }
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-project.txt'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError false
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
